version: '3'

services:
  web:
    build: ./
    tty: true
    command: python3 manage.py runserver 0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pcw
volumes:
  postgres_data:
